# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redisView', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='redisconn',
            unique_together=set([('address', 'port')]),
        ),
    ]
